### PR TITLE
Add overwrite_target_index_token for merging indexes

### PR DESCRIPTION
**Pull request by lkolacek**
CLOUDBLD-4475

Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>

### CODE REVIEW

**Comment by lkolacek** [comment]
PTAL @yashvardhannanavati @pbortlov @lcarva

I believe this will address the issue we're facing in CLOUDBLD-4475.
Can someone provide info to me on how to test locally with quay.io registries so I avoid testing on registry.redhat.io.

**Comment by pbortlov** [comment]
This is connected to #231

**Comment by lcarva** [comment]
Code change looks fine to me. Can we add a unit test for it?

**Comment by lkolacek** [comment]
@lcarva Since set_registry_token has its own unit test - https://github.com/release-engineering/iib/blob/master/tests/test_workers/test_tasks/test_utils.py#L55  

I added only simple check here if method was called.

**Review by midnightercz — APPROVED** [review]

**Review by pbortlov — APPROVED** [review]
+1

**Review by lcarva — APPROVED** [review]

**Comment by lcarva** [comment]
@lkolacek, could you rebase so we can merge this?

**Comment by lkolacek** [comment]
@lcarva done, please merge it.

**Pull request merged**
