### PR TITLE
[Do not merge] Upgrade IIB cryptography package

### PR DESCRIPTION
**Pull request by lkolacek**
Closes CLOUDBLD-4575

Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>

### CODE REVIEW

**Comment by lkolacek** [comment]
Hi @MartinBasti  @yashvardhannanavati,

I added all deps for `cryptography` but I still can't make it work for `Py3.6`.
I also tried to update pip package as it was reccommended in cryptography documentation but nothing seems to work.

Do we really want to run and set the following? And if yes where should I put it?
```
curl https://sh.rustup.rs -sSf | bash -s -- -y
PATH="${HOME}/.cargo/bin:${PATH}"
```

**Comment by lcarva** [comment]
Thanks for doing this! I think we should hold off merging this until IIB itself is running on python 3.8. I wonder if, to make the transition easier, we need a separate PR that simply adds python 3.8 (and maybe remove 3.7?) without upgrading any packages. We will want to ensure the tests work just fine on python 3.8 before upgrading the IIB environment to that version. Wdyt?

**Comment by lkolacek** [comment]
@lcarva  separate PR for adding Py3.8 support and testing the current version of packages sounds good! I updated the description here: https://projects.engineering.redhat.com/browse/CLOUDBLD-5803

I also updated Summary of this PR to non to be accidentally merged.

**Comment by pbortlov** [comment]
@lcarva @yashvardhannanavati @midnightercz @lipoja @querti Could we circle back here? It seems that we can't use the newest versions of libraries which we have to update because of security vulnerabilities. #269

**Comment by MartinBasti** [comment]
> @lcarva @yashvardhannanavati @midnightercz @lipoja @querti Could we circle back here? It seems that we can't use the newest versions of libraries which we have to update because of security vulnerabilities. #269

I don't follow why not, can you elaborate more?

**Comment by lkolacek** [comment]
+1 can you provide more info @pbortlov ? PRs do not seem to be affecting each other at first sight.

**Comment by pbortlov** [comment]
@lkolacek we have a security vulnerability with urllib3 and if I bump the library to the secure version python3.6 is failing. So I was thinking to circle back here if we can open the discussion about python3.8

**Comment by pbortlov** [comment]
@lkolacek @lcarva @yashvardhannanavati @release-engineering/exd-guild-hello-operator 
This PR can be closed because there is no need to upgrade to python 3.8 if you upgrade pip in the IIB. please see #279 #282

**Comment by pbortlov** [comment]
This will be closed in favor of #282

**Pull request closed without merging**
