### PR TITLE
Update opm version to v1.8.0

### PR DESCRIPTION
**Pull request by JayZ12138**
Link to JIRA: https://projects.engineering.redhat.com/browse/CLOUDDST-296

### CODE REVIEW

**Comment by JayZ12138** [comment]
There's an error in sphinx-build. I believe there's an incompatible change from Sphinx v2.4.4, which was used in the last Travis CI check, to Sphinx v3.0.0, which is failing now. 
Due to the network issue, I couldn't update my sphinx version to 3.0.0 locally and fix the problem. If anyone could help, really appreciated!

**Comment by JayZ12138** [comment]
@yashvardhannanavati, not sure who should I invite to review, could you please help?

**Comment by mprahl** [comment]
@JayZ12138 I fixed the error in #58.

**Comment by yashvardhannanavati** [comment]
:+1: 

Thanks Matt and Jay!

**Pull request merged**
